name: Release Obsidian plugin

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18.x"

            - name: Install dependencies and Build plugin
              run: |
                  npm install
                  npm run build

            - name: Create zip
              run: |
                  zip -r plugin.zip main.js manifest.json styles.css

            - name: Create release
              env:
                  GITHUB_TOKEN: ${{ secrets.TOKEN }}
              run: |
                  tag="${GITHUB_REF#refs/tags/}"
                  
                  gh release create "$tag" \
                    --title="$tag" \
                    --draft \
                    plugin.zip
